//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreClientApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfEnter
    {
        public int ID { get; set; }
        public System.DateTime LastEnter { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
