//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreClientApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequest
    {
        public int ID { get; set; }
        public string Product { get; set; }
        public Nullable<int> ProductCount { get; set; }
    }
}
